import { Link } from "react-router-dom";
import DayNav from "../../components/DayNav";
import CodeBlock from "../../components/CodeBlock";

export default function Notes() {
  return (
    <div className="page notes-page">
      <title>Day 14 Notes</title>
      <DayNav day="day14-database-performance" current="notes" />

      <header className="lecture-header">
        <p className="eyebrow">Week 3 · Day 14 · Notes</p>
        <h1>Database Performance</h1>
        <p className="subtitle">Executive summary → full walkthrough</p>
      </header>

      {/* ============================================================ */}
      {/* Section 1 — Executive Summary                                 */}
      {/* ============================================================ */}
      <section id="executive-summary" className="exec-summary">
        <h2>Section 1 — Executive Summary</h2>
        <p>The essentials — what you must be able to do by the end of today:</p>
        <ul>
          <li>
            Spot an N+1 query by reading code, and fix it with a join or a
            batched lookup
          </li>
          <li>
            Add an index for a real slow query and explain what it does — and
            what it costs
          </li>
          <li>
            Read an <code>EXPLAIN ANALYZE</code> plan well enough to tell
            whether an index is being used
          </li>
          <li>
            Explain why deep <code>OFFSET</code> pagination gets slow, and write
            the keyset version instead
          </li>
          <li>
            Explain partitioning, sharding and read replicas conceptually — what
            problem each one solves, and in what order you'd reach for them
          </li>
          <li>
            Use one connection pool per process instead of connecting per
            request, and say why
          </li>
          <li>
            Pick SQL vs. NoSQL for a specific case and justify it (e.g. a
            high-write append-only log)
          </li>
        </ul>
        <p>
          Want more?{" "}
          <Link to="/week3/day14-database-performance/concepts">
            View all concepts?
          </Link>
        </p>
      </section>

      <hr className="section-divider" />

      {/* ============================================================ */}
      {/* Section 2 — Full Walkthrough                                  */}
      {/* ============================================================ */}
      <section id="full-walkthrough">
        <h2>Section 2 — Full Walkthrough</h2>
        <p>
          Everything below works against the schema from Day 12 —{" "}
          <code>orders</code>, <code>order_items</code>, <code>inventory</code>,{" "}
          <code>order_status_history</code>. The snippets use raw{" "}
          <code>pool.query</code> so you can see exactly what reaches the
          database — in the project, that SQL lives in Day 13&apos;s repository
          layer, whether written by hand or generated by the ORM.
        </p>
        <p className="callout">
          Fix in this order: query shape first, then indexes, then capacity.
          Most "we need a bigger database" turns out to be a missing index.
        </p>

        <h3>2.1 The N+1 query problem</h3>
        <p>
          <strong>Problem:</strong> one query fetches a list, then one more
          query runs <em>per row</em> to fetch that row's related data — 1 query
          becomes 1 + N.
        </p>
        <CodeBlock
          language="typescript"
          code={`// BAD — 1 query for the orders, then 1 more query per order for its items
const { rows: orders } = await pool.query('SELECT * FROM orders');

for (const order of orders) {
  const { rows: items } = await pool.query(
    'SELECT * FROM order_items WHERE order_id = $1',
    [order.id]
  );
  order.items = items;
}
// 50 orders on the page = 51 queries`}
        />
        <p>
          <strong>Solution:</strong> one join query instead of looping.
        </p>
        <CodeBlock
          language="typescript"
          code={`// GOOD — one query, joined
const { rows } = await pool.query(\`
  SELECT o.id AS order_id, oi.product_id, oi.quantity, p.name AS product_name
  FROM orders o
  JOIN order_items oi ON oi.order_id = o.id
  JOIN products p ON p.id = oi.product_id
\`);
// 50 orders on the page = 1 query, however many items they have`}
        />
        <p>
          <strong>Or, when the join gets ugly:</strong> fetch the parents, then
          fetch <em>all</em> the children in one batched query.
        </p>
        <CodeBlock
          language="typescript"
          code={`const ids = orders.map((o) => o.id);
const { rows: items } = await pool.query(
  'SELECT * FROM order_items WHERE order_id = ANY($1::int[])',
  [ids]
);
// 2 queries, no matter how many orders came back`}
        />
        <p className="callout">
          N+1 doesn't throw an error or fail a test with 5 rows of seed data —
          it just gets slower and slower as the table grows. Reading the code
          for "a query inside a loop" is the habit that catches it before
          production does.
        </p>
        <p>
          <strong>Other common scenarios of the N+1 problem:</strong>
        </p>
        <CodeBlock
          language="typescript"
          code={`// Promise.all — parallel, but each call still queries individually
await Promise.all(
  orders.map((o) => pool.query('SELECT * FROM order_items WHERE order_id = $1', [o.id]))
);
// N queries firing at once instead of one after another — still N queries

// Hidden inside a helper — the loop looks innocent, the query is one call deeper
const enriched = orders.map((o) => enrichOrder(o));
// enrichOrder itself runs: pool.query('SELECT * FROM order_items WHERE order_id = $1', [o.id])

// ORM lazy loading — each access below silently issues its own query
for (const order of orders) {
  console.log(order.customer.name);
  // behind the scenes: SELECT * FROM customers WHERE id = order.customer_id
}`}
        />
        <p>
          All of these, and the ORM eager-loading fixes, are in{" "}
          <Link to="/week3/additional-backend-topics/full-sql/query-optimization">
            Full SQL · Query Optimization
          </Link>
          .
        </p>

        <h3>2.2 Indexing</h3>
        <p>
          <strong>Problem:</strong> without an index, finding matching rows
          means reading every row in the table and checking each one.
        </p>
        <CodeBlock
          language="sql"
          code={`SELECT * FROM orders WHERE status = 'packed';
-- with no index: Postgres reads every row in orders and checks each one`}
        />
        <p>
          <strong>Solution: an index.</strong> A separate, sorted structure
          Postgres keeps next to the table — roughly a B-tree, the same shape
          Postgres uses internally — so it can jump straight to the matching
          rows instead of reading every one.
        </p>
        <CodeBlock
          language="sql"
          code={`CREATE INDEX orders_status_idx ON orders (status);`}
        />
        <CodeBlock
          language="plaintext"
          code={`orders has 5,000,000 rows

WITHOUT an index                     WITH an index on (status)
─────────────────────                ──────────────────────────
check row 1          → no match      jump straight to the rows
check row 2          → no match      where status = 'packed'
check row 3          → MATCH                  │
...                   ...                     ▼
check row 4,999,999  → no match      found — done
check row 5,000,000  → no match

5,000,000 rows checked               a small handful checked`}
        />
        <p className="callout">
          On 5 seed rows this makes no visible difference — the gap only shows
          up at real scale. The actual before/after timing is in the next
          section's <code>EXPLAIN</code> plan.
        </p>
        <p>
          <strong>Trade-off:</strong> an index isn't free — every index on a
          table is more work for every write to it:
        </p>
        <CodeBlock
          language="sql"
          code={`-- orders now has 2 indexes: (status), (created_at)
UPDATE orders SET status = 'shipped' WHERE id = 42;
-- this one UPDATE writes the row, then updates both indexes too`}
        />
        <div className="concept">
          <p className="concept-label">Concept — indexing in one sentence</p>
          <ul>
            <li>
              An index is a separate, sorted lookup structure Postgres keeps
              next to a table.
            </li>
            <li>
              <strong>Benefit:</strong> faster reads — jump straight to matching
              rows instead of scanning every one.
            </li>
            <li>
              <strong>Trade-off:</strong> slower writes — every{" "}
              <code>INSERT</code>/<code>UPDATE</code>/<code>DELETE</code> on the
              table also updates every index on it.
            </li>
            <li>
              In short: an index speeds up the read and slows down the write.
              Index the columns you actually filter or join on, not every column
              in the table.
            </li>
          </ul>
        </div>
        <p>
          A query can filter on more than one column at once — indexing several
          columns together (a compound index) and the leftmost-prefix rule that
          comes with it are in{" "}
          <Link to="/week3/additional-backend-topics/full-sql/query-optimization">
            Full SQL · Query Optimization
          </Link>
          .
        </p>
        <figure className="video-embed">
          <iframe
            src="https://www.youtube.com/embed/lYh6LrSIDvY"
            title="Database indexing explained"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowFullScreen
          />
        </figure>

        <h3>
          2.3 Reading an <code>EXPLAIN</code> plan
        </h3>
        <p>
          <strong>Step 1 — find the slow query.</strong> In production you won't
          know which one to look at unless something tells you:
        </p>
        <CodeBlock
          language="plaintext"
          code={`log_min_duration_statement = 100   -- log any statement slower than 100ms, with its duration`}
        />
        <p>
          Once that's on, a slow query shows up as a line in the Postgres log:
        </p>
        <CodeBlock
          language="plaintext"
          code={`2026-03-14 10:02:11 UTC LOG:  duration: 812.441 ms  statement: SELECT * FROM orders WHERE status = 'packed';`}
        />
        <p>
          <code>pg_stat_statements</code> goes further — it's a real table
          Postgres keeps, so you can query it directly instead of reading log
          files one line at a time:
        </p>
        <CodeBlock
          language="sql"
          code={`SELECT calls, round(mean_exec_time::numeric, 2) AS avg_ms, query
FROM pg_stat_statements
ORDER BY mean_exec_time * calls DESC
LIMIT 3;`}
        />
        <CodeBlock
          language="plaintext"
          code={`calls | avg_ms | query
------+--------+------------------------------------------------
 4021 | 210.30 | SELECT * FROM orders WHERE status = $1
  980 | 812.44 | SELECT * FROM orders o JOIN customers c ON ...
  512 |  45.02 | SELECT * FROM inventory WHERE store_id = $1`}
        />
        <p className="callout">
          This is how real performance problems get found — reading the logs (or{" "}
          <code>pg_stat_statements</code>) for what's actually slow, not by
          guessing which query "feels slow" while writing it.
        </p>
        <p>
          <strong>Step 2 — look inside it.</strong> <code>EXPLAIN ANALYZE</code>{" "}
          runs the query for real and prints the plan Postgres used, with real
          timings:
        </p>
        <CodeBlock
          language="sql"
          code={`EXPLAIN ANALYZE SELECT * FROM orders WHERE status = 'packed';`}
        />
        <p>
          On the 5,000,000-row <code>orders</code> table from the last section,
          before the index exists:
        </p>
        <CodeBlock
          language="plaintext"
          code={`Seq Scan on orders  (cost=0.00..104000.00 rows=1180 width=48) (actual time=0.412..812.330 rows=1204 loops=1)
  Filter: ((status)::text = 'packed'::text)
  Rows Removed by Filter: 4998796
Planning Time: 0.110 ms
Execution Time: 812.441 ms`}
        />
        <p>How to read it, piece by piece:</p>
        <table className="ref-table">
          <thead>
            <tr>
              <th>Part</th>
              <th>What it means</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <code>Seq Scan on orders</code>
              </td>
              <td>
                The operation. <code>Seq Scan</code> = read every row.{" "}
                <code>Index Scan</code> / <code>Bitmap Index Scan</code> = used
                an index.
              </td>
            </tr>
            <tr>
              <td>
                <code>cost=0.00..104000.00</code>
              </td>
              <td>
                The planner's <em>estimate</em> (first row..all rows), in its
                own units — not milliseconds. Only useful for comparing plans.
              </td>
            </tr>
            <tr>
              <td>
                <code>rows=1180 width=48</code>
              </td>
              <td>
                Estimated rows returned, and average row size in bytes.
              </td>
            </tr>
            <tr>
              <td>
                <code>actual time=0.412..812.330</code>
              </td>
              <td>Real milliseconds: first row..last row.</td>
            </tr>
            <tr>
              <td>
                <code>rows=1204 loops=1</code>
              </td>
              <td>
                Rows actually returned, and how many times this step ran. If
                actual rows are far off the estimate, the planner's stats are
                stale — run <code>ANALYZE orders;</code>.
              </td>
            </tr>
            <tr>
              <td>
                <code>Filter</code>
              </td>
              <td>The condition checked against each row after reading it.</td>
            </tr>
            <tr>
              <td>
                <code>Rows Removed by Filter</code>
              </td>
              <td>
                Rows read, then thrown away. A big number here = missing index.
              </td>
            </tr>
            <tr>
              <td>
                <code>Planning Time</code> / <code>Execution Time</code>
              </td>
              <td>
                Time spent choosing the plan / actually running it. Execution
                Time is the one to watch.
              </td>
            </tr>
          </tbody>
        </table>
        <p>
          Put together: Postgres read all 5,000,000 rows, kept 1,204, threw away
          the other 4,998,796 — and took 812ms doing it. After{" "}
          <code>CREATE INDEX orders_status_idx ON orders (status);</code>:
        </p>
        <CodeBlock
          language="plaintext"
          code={`Index Scan using orders_status_idx on orders  (cost=0.43..1250.20 rows=1180 width=48) (actual time=0.031..0.290 rows=1204 loops=1)
  Index Cond: ((status)::text = 'packed'::text)
Planning Time: 0.120 ms
Execution Time: 0.312 ms`}
        />
        <p className="callout">
          Same 1,204 rows, 812ms → 0.3ms. <code>Index Cond</code> replaced{" "}
          <code>Filter</code>, and there's no <code>Rows Removed</code> line —
          it jumped straight to the matches instead of reading everything.
        </p>
        <div className="concept">
          <p className="concept-label">Summary — fixing a slow query</p>
          <ol>
            <li>
              <strong>Find it:</strong> <code>pg_stat_statements</code> records
              the call count and timing of every query. Sort it by average (or
              total) time to get the top few offenders.
            </li>
            <li>
              <strong>Explain it:</strong> run <code>EXPLAIN ANALYZE</code> on
              that query. <code>Seq Scan</code> + big{" "}
              <code>Rows Removed by Filter</code> → add an index.
            </li>
            <li>
              <strong>Confirm it:</strong> run <code>EXPLAIN ANALYZE</code>{" "}
              again — you should see an <code>Index Scan</code> and a much
              smaller Execution Time.
            </li>
          </ol>
        </div>
        <p>
          A worked 812ms → 0.3ms plan on a real-sized table, every node type
          you'll see, and why an index you created might still not be used are
          in{" "}
          <Link to="/week3/additional-backend-topics/full-sql/query-optimization">
            Full SQL · Query Optimization
          </Link>
          .
        </p>

        <h3>
          2.4 Pagination: <code>OFFSET</code> vs. keyset
        </h3>
        <p>
          The fulfillment queue is paginated. The obvious way stops working on
          deep pages:
        </p>
        <CodeBlock
          language="sql"
          code={`SELECT * FROM orders ORDER BY created_at DESC LIMIT 20 OFFSET 9980;   -- page 500`}
        />
        <div className="concept">
          <p className="concept-label">Concept — two problems, both real</p>
          <ul>
            <li>
              <strong>It gets slower the deeper you go.</strong> The database
              still has to produce and discard all 9,980 skipped rows before
              returning 20. Page 1 is instant; page 500 is a scan and a sort.
            </li>
            <li>
              <strong>It skips and duplicates rows under writes.</strong> A new
              order inserted while the user is on page 2 shifts everything down
              one, so row 20 reappears on page 3.
            </li>
            <li>
              It's still right when you need numbered pages and a total count.
              It's wrong for infinite scroll and for anything paging through a
              big table.
            </li>
          </ul>
        </div>
        <p>
          Keyset (cursor) pagination replaces "skip 9,980 rows" with "start
          after the last row I saw", so the index seeks straight there and page
          500 costs the same as page 1:
        </p>
        <CodeBlock
          language="sql"
          code={`-- page 1
SELECT id, created_at, status FROM orders
ORDER BY created_at DESC, id DESC
LIMIT 20;

-- page 2 — pass the last row's sort key back as the cursor
SELECT id, created_at, status FROM orders
WHERE (created_at, id) < ('2026-03-14 10:02:11+00', 4012)
ORDER BY created_at DESC, id DESC
LIMIT 20;`}
        />
        <p className="callout">
          The sort key needs a unique tiebreaker (<code>id</code>) and an index
          on exactly that key — paginating on <code>created_at</code> alone
          silently loses rows whenever two share a timestamp.
        </p>

        <h3>2.5 Partitioning, sharding &amp; replication</h3>
        <p>
          <strong>Problem:</strong> a table that's fast at 5,000 rows can slow to a crawl at 5
          million — more rows to scan, more index to maintain, more writes competing for the same
          machine.
        </p>
        <p>Three different fixes for three different flavors of that problem — not synonyms:</p>
        <table className="ref-table">
          <thead>
            <tr>
              <th>Technique</th>
              <th>What it does</th>
              <th>Problem it solves</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Partitioning</td>
              <td>
                Splits one table into smaller physical tables by a key (usually
                a date), inside <strong>one</strong> database
              </td>
              <td>One table so big its scans and its maintenance hurt</td>
            </tr>
            <tr>
              <td>Sharding</td>
              <td>
                Splits rows across <strong>separate database servers</strong> by
                a shard key
              </td>
              <td>Write volume or data size beyond one machine</td>
            </tr>
            <tr>
              <td>Replication</td>
              <td>
                Copies the same data to read-only replicas that follow the
                primary
              </td>
              <td>Read load, and failover if the primary dies</td>
            </tr>
          </tbody>
        </table>

        <p>
          <strong>Partitioning</strong> — split one big table into smaller
          physical tables by a key, still inside one database:
        </p>
        <svg viewBox="0 0 640 235" role="img" aria-label="One Postgres database containing the order_status_history table split into partitions osh_2026_01, osh_2026_02, osh_2026_03 and more. A date-filtered query only touches the osh_2026_02 partition.">
          <defs>
            <marker id="part-arrow" viewBox="0 0 10 10" refX="5" refY="8" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
              <path d="M0,10 L5,0 L10,10 z" fill="#2255cc" />
            </marker>
          </defs>
          <rect x="20" y="15" width="600" height="140" rx="10" fill="#fafafa" stroke="#ccc" strokeWidth="1.5" strokeDasharray="5 4" />
          <text x="34" y="35" fontSize="11" fontWeight="700" fill="#5b6b82">ONE Postgres database</text>
          <text x="320" y="55" textAnchor="middle" fontSize="12" fontWeight="700" fill="#1c1c1c">order_status_history</text>
          <rect x="45" y="68" width="125" height="60" rx="6" fill="#eef3ff" stroke="#7ea6e0" strokeWidth="1.5" />
          <text x="107" y="103" textAnchor="middle" fontSize="11" fill="#1c1c1c">osh_2026_01</text>
          <rect x="185" y="68" width="125" height="60" rx="6" fill="#dceaff" stroke="#2255cc" strokeWidth="2.5" />
          <text x="247" y="103" textAnchor="middle" fontSize="11" fontWeight="700" fill="#1c1c1c">osh_2026_02</text>
          <rect x="325" y="68" width="125" height="60" rx="6" fill="#eef3ff" stroke="#7ea6e0" strokeWidth="1.5" />
          <text x="387" y="103" textAnchor="middle" fontSize="11" fill="#1c1c1c">osh_2026_03</text>
          <rect x="465" y="68" width="110" height="60" rx="6" fill="#eef3ff" stroke="#7ea6e0" strokeWidth="1.5" />
          <text x="520" y="103" textAnchor="middle" fontSize="16" fill="#1c1c1c">…</text>
          <path d="M247,205 L247,163" fill="none" stroke="#2255cc" strokeWidth="2" markerEnd="url(#part-arrow)" />
          <text x="247" y="220" textAnchor="middle" fontSize="10" fill="#2255cc">a date-filtered query touches only this one</text>
        </svg>
        <p>
          A query with no date filter has to check every partition instead of just one, and
          dropping a month of old data becomes a <code>DROP TABLE</code>, not a multi-hour{" "}
          <code>DELETE</code>:
        </p>
        <CodeBlock
          language="sql"
          code={`CREATE TABLE order_status_history (
  id BIGSERIAL,
  order_id INTEGER NOT NULL,
  to_status VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
) PARTITION BY RANGE (created_at);

CREATE TABLE osh_2026_02 PARTITION OF order_status_history
  FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');`}
        />
        <p className="callout">
          Still one machine — partitioning never adds write capacity, it only
          makes queries that filter on the partition key cheaper.
        </p>

        <p>
          <strong>Sharding</strong> — split rows across separate database{" "}
          <em>servers</em> by a shard key:
        </p>
        <svg viewBox="0 0 640 220" role="img" aria-label="An app routing a lookup for customer 1500 to Shard 2 only, out of three separate Postgres servers each holding a different range of customer IDs.">
          <defs>
            <marker id="shard-arrow-blue" viewBox="0 0 10 10" refX="5" refY="8" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
              <path d="M0,10 L5,0 L10,10 z" fill="#2255cc" />
            </marker>
            <marker id="shard-arrow-gray" viewBox="0 0 10 10" refX="5" refY="8" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
              <path d="M0,10 L5,0 L10,10 z" fill="#bbb" />
            </marker>
          </defs>
          <rect x="270" y="15" width="100" height="40" rx="6" fill="#fff7e0" stroke="#e8b400" strokeWidth="1.5" />
          <text x="320" y="40" textAnchor="middle" fontSize="12" fontWeight="700" fill="#1c1c1c">app</text>
          <path d="M320,55 Q220,78 130,98" fill="none" stroke="#bbb" strokeWidth="1.5" strokeDasharray="4 3" markerEnd="url(#shard-arrow-gray)" />
          <path d="M320,55 L320,98" fill="none" stroke="#2255cc" strokeWidth="2.5" markerEnd="url(#shard-arrow-blue)" />
          <path d="M320,55 Q420,78 510,98" fill="none" stroke="#bbb" strokeWidth="1.5" strokeDasharray="4 3" markerEnd="url(#shard-arrow-gray)" />
          <text x="330" y="78" fontSize="10" fill="#2255cc">customer 1500</text>
          <rect x="45" y="100" width="170" height="90" rx="8" fill="#eef3ff" stroke="#7ea6e0" strokeWidth="1.5" />
          <text x="130" y="128" textAnchor="middle" fontSize="12" fontWeight="700" fill="#1c1c1c">Shard 1</text>
          <text x="130" y="145" textAnchor="middle" fontSize="9" fill="#5b6b82">customer_id 1–1000</text>
          <text x="130" y="160" textAnchor="middle" fontSize="9" fill="#5b6b82">full Postgres server</text>
          <rect x="235" y="100" width="170" height="90" rx="8" fill="#dceaff" stroke="#2255cc" strokeWidth="2.5" />
          <text x="320" y="128" textAnchor="middle" fontSize="12" fontWeight="700" fill="#1c1c1c">Shard 2</text>
          <text x="320" y="145" textAnchor="middle" fontSize="9" fill="#5b6b82">customer_id 1001–2000</text>
          <text x="320" y="160" textAnchor="middle" fontSize="9" fill="#5b6b82">full Postgres server</text>
          <rect x="425" y="100" width="170" height="90" rx="8" fill="#eef3ff" stroke="#7ea6e0" strokeWidth="1.5" />
          <text x="510" y="128" textAnchor="middle" fontSize="12" fontWeight="700" fill="#1c1c1c">Shard 3</text>
          <text x="510" y="145" textAnchor="middle" fontSize="9" fill="#5b6b82">customer_id 2001–3000</text>
          <text x="510" y="160" textAnchor="middle" fontSize="9" fill="#5b6b82">full Postgres server</text>
        </svg>
        <p>
          A lookup for customer 1500 only ever reaches Shard 2 — the other two are never queried.
          The cost: two rows on different shards can't be joined in one query, so anything
          spanning shards moves into application code.
        </p>
        <p className="callout">
          Cross-shard joins and transactions move into application code. Picking
          the shard key wrong (a hot shard, a query that needs every shard) is
          expensive to undo.
        </p>

        <p>
          <strong>Replication</strong> — copy the same data to read-only
          replicas that follow the primary:
        </p>
        <svg viewBox="0 0 640 210" role="img" aria-label="A primary database accepting writes, replicating asynchronously to two read-only replicas that serve read traffic.">
          <defs>
            <marker id="replica-arrow" viewBox="0 0 10 10" refX="5" refY="8" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
              <path d="M0,10 L5,0 L10,10 z" fill="#e8b400" />
            </marker>
          </defs>
          <rect x="250" y="15" width="140" height="55" rx="8" fill="#fff7e0" stroke="#e8b400" strokeWidth="2" />
          <text x="320" y="38" textAnchor="middle" fontSize="13" fontWeight="700" fill="#1c1c1c">PRIMARY</text>
          <text x="320" y="55" textAnchor="middle" fontSize="9" fill="#5b6b82">the only place that accepts writes</text>
          <path d="M320,70 Q240,105 178,140" fill="none" stroke="#e8b400" strokeWidth="2" markerEnd="url(#replica-arrow)" />
          <path d="M320,70 Q400,105 462,140" fill="none" stroke="#e8b400" strokeWidth="2" markerEnd="url(#replica-arrow)" />
          <text x="320" y="108" textAnchor="middle" fontSize="10" fill="#5b6b82">async replication (lag: ms – seconds)</text>
          <rect x="90" y="140" width="170" height="60" rx="8" fill="#eef3ff" stroke="#7ea6e0" strokeWidth="1.5" />
          <text x="175" y="165" textAnchor="middle" fontSize="12" fontWeight="700" fill="#1c1c1c">Replica A</text>
          <text x="175" y="182" textAnchor="middle" fontSize="9" fill="#5b6b82">read-only</text>
          <rect x="380" y="140" width="170" height="60" rx="8" fill="#eef3ff" stroke="#7ea6e0" strokeWidth="1.5" />
          <text x="465" y="165" textAnchor="middle" fontSize="12" fontWeight="700" fill="#1c1c1c">Replica B</text>
          <text x="465" y="182" textAnchor="middle" fontSize="9" fill="#5b6b82">read-only</text>
        </svg>
        <p>
          Reserve stock on the primary, then immediately read it back from a replica, and it might
          still show the old number — read-after-write has to go to the primary.
        </p>
        <p className="callout">
          Replication solves read load and failover, not write capacity — every
          write still goes through the one primary.
        </p>

        <p className="callout">
          Order of reach: index → batch → cache → replica → partition → shard.
          Shard last; one well-indexed Postgres handles far more than most teams
          assume.
        </p>
        <p>
          The deeper version — partition strategies and pruning, choosing a
          shard key, replication lag and read-your-writes — is in{" "}
          <Link to="/week3/additional-backend-topics/full-sql/scaling-and-throughput">
            Full SQL · Scaling &amp; Throughput
          </Link>
          .
        </p>

        <h3>2.6 Connection pooling</h3>
        <p>
          A Postgres connection is a separate OS process with several MB of
          memory behind it. Opening one per request costs a TCP handshake plus
          authentication plus process startup — routinely more than the query
          itself.
        </p>
        <CodeBlock
          language="typescript"
          bad={[4, 5, 6]}
          good={[11]}
          code={`import { Pool, Client } from "pg";

// BAD — a fresh connection per request
const client = new Client({ connectionString: process.env.DATABASE_URL });
await client.connect();
await client.query("SELECT 1");
await client.end();

// GOOD — one pool per process, created once at startup
export const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  max: 10,                        // connections this process may hold
  idleTimeoutMillis: 30_000,
  connectionTimeoutMillis: 2_000, // fail fast instead of queueing forever
});

await pool.query("SELECT 1");     // borrow, run, return — transparently`}
        />
        <CodeBlock
          language="typescript"
          code={`// a transaction must run every statement on the SAME connection, so check one out
const client = await pool.connect();
try {
  await client.query("BEGIN");
  await client.query("UPDATE inventory SET quantity_reserved = quantity_reserved + $1 WHERE id = $2", [3, 42]);
  await client.query("INSERT INTO orders (customer_id, status) VALUES ($1, 'routed')", [7]);
  await client.query("COMMIT");
} catch (err) {
  await client.query("ROLLBACK");
  throw err;
} finally {
  client.release();   // without this the connection leaks and the pool starves
}`}
        />
        <p className="callout">
          The pool is per process: 8 app instances × <code>max: 10</code> = 80
          connections at the database, which must stay under its{" "}
          <code>max_connections</code>. Bigger pools aren't faster — past the
          point where the database is CPU-bound they just add contention.
        </p>

        <h3>2.7 SQL vs. NoSQL</h3>
        <p>The high-level differences, at a glance:</p>
        <table className="ref-table">
          <thead>
            <tr>
              <th></th>
              <th>SQL</th>
              <th>NoSQL</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Data shape</td>
              <td>Rows in tables, a fixed schema</td>
              <td>Documents / key-value / etc., flexible per record</td>
            </tr>
            <tr>
              <td>Relationships</td>
              <td>Joined across tables at query time</td>
              <td>Usually embedded together instead of joined</td>
            </tr>
            <tr>
              <td>Consistency</td>
              <td>Strong — ACID transactions</td>
              <td>Often eventual; tunable depending on the system</td>
            </tr>
            <tr>
              <td>Scaling</td>
              <td>Vertical first, then replicas/sharding</td>
              <td>Built to scale out horizontally from the start</td>
            </tr>
            <tr>
              <td>Best at</td>
              <td>Complex queries over related data</td>
              <td>Very high throughput, simple lookups by key</td>
            </tr>
          </tbody>
        </table>

        <p>A closer look, with the same kind of data modeled both ways:</p>

        <p>
          <strong>Schema:</strong> SQL fixes the shape up front; NoSQL lets
          every record have its own shape.
        </p>
        <CodeBlock
          language="sql"
          code={`CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  author_id INTEGER NOT NULL REFERENCES authors(id),
  published_at TIMESTAMPTZ
);
-- every row has exactly these columns, always`}
        />
        <CodeBlock
          language="json"
          code={`{
  "id": "post_1",
  "title": "...",
  "author": { "name": "Ana" },
  "tags": ["sql", "databases"]
}
// the next document can have completely different fields`}
        />

        <p>
          <strong>Relationships:</strong> SQL joins across tables at query time;
          NoSQL usually embeds the related data directly in the record instead.
        </p>
        <CodeBlock
          language="sql"
          code={`SELECT posts.title, authors.name
FROM posts
JOIN authors ON authors.id = posts.author_id;`}
        />
        <CodeBlock
          language="json"
          code={`{ "title": "...", "author": { "name": "Ana" } }
// the author's name is already inside the post — no join needed, but it's
// now duplicated across every post that author has written`}
        />

        <p>
          <strong>Consistency:</strong> SQL guarantees a transaction is
          all-or-nothing and every read sees committed data. Many NoSQL systems
          trade that for speed — a write can take a moment to become visible
          everywhere, which is fine for some data (a "like" count) and wrong for
          others (an account balance).
        </p>
        <p>
          Every NoSQL family, ACID vs. BASE in more depth, and the same domain
          modeled both ways are in{" "}
          <Link to="/week3/additional-backend-topics/full-sql/sql-vs-nosql">
            Full SQL · SQL vs. NoSQL
          </Link>
          .
        </p>
      </section>
    </div>
  );
}
